bot:
  name:
  token:
spring:
  datasource:
    url:
    driver-class-name: org.postgresql.Driver
    initialization-mode: never
    username:
    password:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update


