bot:
  name: TestAokBot
  token: 1865100140:AAHkwAAglGt-gSriTDQEvX3ukfhdULp4UZY
spring:
  datasource:
    url:
    driver-class-name:
    initialization-mode: never
    username:
    password:
  jpa:
    database-platform:
    show-sql: true
    hibernate:
      ddl-auto: update



